### PR TITLE
Fix Splunk GDI specification badge

### PR DESCRIPTION
**Pull request by pellared**

### CODE REVIEW

**Comment by Kielek** [comment]
#180

**Comment by pellared** [comment]
@Kielek Why have you closed the PR? Take notice that the badge renders incorrect version.

**Comment by Kielek** [comment]
https://github.com/signalfx/splunk-otel-ios/pull/181#issuecomment-1786549672, you are too slow ;- )

**Comment by pellared** [comment]
Now I see. I saw a wrong PR 😉

**Pull request closed without merging**
